- type: replace
  path: /instance_groups/name=scheduler/jobs/name=loggr-metric-scraper?
  value:
    name: loggr-metric-scraper
    release: loggregator-agent
    properties:
      system_metrics:
        tls:
          ca_cert: "((system_metrics.ca))"
          cert: "((system_metrics.certificate))"
          key: "((system_metrics.private_key))"
