#####################
# Loggregator Agent #
#####################
- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/properties/grpc_port?
  value: 3459

###################
# Forwarder Agent #
###################
- type: replace
  path: /addons/-
  value:
    name: loggr-syslog-agent
    include:
      stemcell:
      - os: ubuntu-trusty
      - os: ubuntu-xenial
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: loggr-forwarder-agent
      release: loggregator-agent
      properties:
        downstream_ingress_ports:
        - 3459
        - 3460
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"
    - name: loggr-syslog-agent
      release: loggregator-agent
      properties:
        port: 3460
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"
        api:
          tls:
            ca_cert: "((service_cf_internal_ca.certificate))"
            cert: "((forwarder_agent_api_tls.certificate))"
            key: "((forwarder_agent_api_tls.private_key))"
            cn: "cloud-controller-ng.service.cf.internal"

- type: replace
  path: /variables/-
  value:
    name: forwarder_agent_api_tls
    type: certificate
    options:
      ca: service_cf_internal_ca
      common_name: forwarder-agent
      extended_key_usage:
      - client_auth

#################
# UDP Forwarder #
#################
- type: replace
  path: /addons/name=loggregator_agent/exclude/jobs?/-
  value:
    name: cloud_controller_ng
    release: capi

- type: replace
  path: /instance_groups/name=api/jobs/name=loggregator_agent?
  value:
    name: loggregator_agent
    release: loggregator-agent
    properties:
      grpc_port: 3459
      disable_udp: true
      loggregator:
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          agent:
            cert: "((loggregator_tls_agent.certificate))"
            key: "((loggregator_tls_agent.private_key))"

- type: replace
  path: /instance_groups/name=api/jobs/-
  value:
    name: loggr-udp-forwarder
    release: loggregator-agent
    properties:
      loggregator:
        tls:
          ca: "((loggregator_ca.certificate))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"
          cn: "cloud-controller-ng.service.cf.internal"
