- type: replace
  path: /addons/-
  value:
    name: forwarder_agent
    include:
      stemcell:
      - os: ubuntu-trusty
      - os: ubuntu-xenial
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: forwarder_agent
      release: loggregator-agent
