#####################
# Loggregator Agent #
#####################
- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/properties/grpc_port?
  value: 3459

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggregator_agent/properties/disable_udp?
  value: true

###################
# Forwarder Agent #
###################
- type: replace
  path: /addons/-
  value:
    name: loggr-syslog-agent
    include:
      stemcell:
      - os: ubuntu-trusty
      - os: ubuntu-xenial
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: loggr-forwarder-agent
      release: loggregator-agent
      properties:
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"
    - name: loggr-syslog-agent
      release: loggregator-agent
      properties:
        port: 3460
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"
        cache:
          tls:
            ca_cert: "((loggregator_ca.certificate))"
            cert: "((syslog_agent_api_tls.certificate))"
            key: "((syslog_agent_api_tls.private_key))"
            cn: "binding-cache"
    - name: prom_scraper
      release: loggregator-agent
      properties:
        metrics_urls: http://localhost:14822/metrics,http://localhost:14823/metrics

- type: replace
  path: /variables/-
  value:
    name: syslog_agent_api_tls
    type: certificate
    options:
      ca: loggregator_ca
      common_name: syslog-agent
      extended_key_usage:
      - client_auth

#################
# Binding Cache #
#################
- type: replace
  path: /instance_groups/name=scheduler/jobs/-
  value:
    name: loggr-syslog-binding-cache
    release: loggregator-agent
    properties:
      external_port: 9000
      tls:
        ca_cert: "((loggregator_ca.certificate))"
        cert: "((binding_cache_tls.certificate))"
        key: "((binding_cache_tls.private_key))"
        cn: "binding-cache"
      api:
        tls:
          ca_cert: "((service_cf_internal_ca.certificate))"
          cert: "((binding_cache_api_tls.certificate))"
          key: "((binding_cache_api_tls.private_key))"
          cn: "cloud-controller-ng.service.cf.internal"

- type: replace
  path: /variables/-
  value:
    name: binding_cache_api_tls
    type: certificate
    options:
      ca: service_cf_internal_ca
      common_name: binding-cache
      extended_key_usage:
      - client_auth

- type: replace
  path: /variables/-
  value:
    name: binding_cache_tls
    type: certificate
    options:
      ca: loggregator_ca
      common_name: binding-cache
      extended_key_usage:
      - server_auth

#################
# UDP Forwarder #
#################
- type: replace
  path: /instance_groups/name=api/jobs/-
  value:
    name: loggr-udp-forwarder
    release: loggregator-agent
    properties:
      loggregator:
        tls:
          ca: "((loggregator_ca.certificate))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"

- type: replace
  path: /instance_groups/name=router/jobs/-
  value:
    name: loggr-udp-forwarder
    release: loggregator-agent
    properties:
      loggregator:
        tls:
          ca: "((loggregator_ca.certificate))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"

- type: replace
  path: /instance_groups/name=tcp-router/jobs/-
  value:
    name: loggr-udp-forwarder
    release: loggregator-agent
    properties:
      loggregator:
        tls:
          ca: "((loggregator_ca.certificate))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"

