###################
# Forwarder Agent #
###################
- type: replace
  path: /addons/-
  value:
    name: forwarder_agent
    include:
      stemcell:
      - os: ubuntu-trusty
      - os: ubuntu-xenial
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: forwarder_agent
      release: loggregator-agent
      properties:
        api:
          tls:
            ca: "((service_cf_internal_ca.certificate))"
            cert: "((forwarder_agent_api_tls.certificate))"
            key: "((forwarder_agent_api_tls.private_key))"
            cn: "cloud-controller-ng.service.cf.internal"

- type: replace
  path: /variables/-
  value:
    name: forwarder_agent_api_tls
    type: certificate
    options:
      ca: service_cf_internal_ca
      common_name: forwarder-agent
      extended_key_usage:
      - client_auth

#################
# UDP Forwarder #
#################
- type: replace
  path: /addons/name=loggregator_agent/exclude/jobs/-
  value:
    name: cloud_controller_ng
    release: capi

- type: replace
  path: /instance_groups/name=api/jobs/-
  value:
    name: udp_forwarder
    release: loggregator-agent
    properties:
      loggregator:
        tls:
          ca: "((loggregator_ca.certificate))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"
          cn: "cloud-controller-ng.service.cf.internal"
