- type: replace
  path: /addons/-
  value:
    name: syslog_agent
    include:
      stemcell:
      - os: ubuntu-trusty
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: syslog_agent
      release: loggregator-agent
