- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggr-forwarder-agent-windows?
  value:
    name: loggr-forwarder-agent-windows
    release: loggregator-agent
    properties:
      tls:
        ca_cert: "((loggregator_ca.certificate))"
        cert: "((loggregator_tls_agent.certificate))"
        key: "((loggregator_tls_agent.private_key))"

- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggregator_agent_windows?
  value:
    name: loggregator_agent_windows
    release: loggregator-agent
    properties:
      grpc_port: 3459
      loggregator:
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          agent:
            cert: "((loggregator_tls_agent.certificate))"
            key: "((loggregator_tls_agent.private_key))"
      syslog_daemon_config:
        enable: false

- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggr-syslog-agent-windows?
  value:
    name: loggr-syslog-agent-windows
    release: loggregator-agent
    properties:
      port: 3460
      tls:
        ca_cert: "((loggregator_ca.certificate))"
        cert: "((loggregator_tls_agent.certificate))"
        key: "((loggregator_tls_agent.private_key))"
      cache:
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          cert: "((syslog_agent_api_tls.certificate))"
          key: "((syslog_agent_api_tls.private_key))"
          cn: "binding-cache"

#Delete ME
- type: replace
  path: /releases/name=loggregator-agent
  value:
    name: loggregator-agent
    version: latest
