- type: replace
  path: /addons/name=loggr-metrics-agent?
  value:
    name: loggr-metrics-agent
    include:
      stemcell:
      - os: ubuntu-xenial
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: loggr-metrics-agent
      release: loggregator-agent
      properties:
        grpc:
          ca_cert: "((loggregator_tls_agent.ca))"
          cert: "((loggregator_tls_agent.certificate))"
          key: "((loggregator_tls_agent.private_key))"
        metrics:
          ca_cert: "((metrics_agent_tls.ca))"
          cert: "((metrics_agent_tls.certificate))"
          key: "((metrics_agent_tls.private_key))"

- type: replace
  path: /variables/name=metric_scraper_ca?
  value:
    name: metric_scraper_ca
    type: certificate
    options:
      is_ca: true
      common_name: metricScraperCA

- type: replace
  path: /variables/name=metrics_agent_tls?
  value:
    name: metrics_agent_tls
    type: certificate
    options:
      ca: metric_scraper_ca
      common_name: metrics_agent
      extended_key_usage:
      - server_auth
      - client_auth
