- type: replace
  path: /releases/name=loggregator-agent
  value:
    name: loggregator-agent
    version: latest

- type: replace
  path: /instance_groups/name=doppler/jobs/name=doppler/provides/loggregator?
  value:
    as: loggregator
    shared: true
