- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/counters/-
  value:
    addr: http://127.0.0.1:14823/debug/vars
    name: ingress
    source_id: forwarder_agent
    template: "{{.ForwarderAgent.IngressV2}}"
    tags:
      origin: loggregator.forwarder_agent
      metric_version: "2.0"

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/counters/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: ingress
    source_id: syslog_agent
    template: "{{.SyslogAgent.IngressV2}}"
    tags:
      origin: loggregator.syslog_agent
      metric_version: "2.0"
      scope: agent

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/counters/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: origin_mappings
    source_id: syslog_agent
    template: "{{.SyslogAgent.OriginMappingsV2}}"
    tags:
      origin: loggregator.syslog_agent
      metric_version: "2.0"

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/counters/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: dropped
    source_id: syslog_agent
    template: "{{.SyslogAgent.IngressDropped}}"
    tags:
      origin: loggregator.syslog_agent
      direction: ingress

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/counters/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: binding_refresh_count
    source_id: syslog_agent
    template: "{{.SyslogAgent.BindingRefreshCount}}"
    tags:
      origin: loggregator.syslog_agent

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/counters/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: binding_refresh_failure_count
    source_id: syslog_agent
    template: "{{.SyslogAgent.BindingRefreshFailureCount}}"
    tags:
      origin: loggregator.syslog_agent

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/gauges/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: drains
    unit: count
    source_id: syslog_agent
    template: "{{.SyslogAgent.DrainCount}}"
    tags:
      origin: loggregator.syslog_agent

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/gauges/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: request_count_for_last_binding_refresh
    unit: requests
    source_id: syslog_agent
    template: "{{.SyslogAgent.RequestCountForLastBindingRefresh}}"
    tags:
      origin: loggregator.syslog_agent

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/gauges/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: max_latency_for_last_binding_refresh
    unit: ms
    source_id: syslog_agent
    template: "{{.SyslogAgent.MaxLatencyForLastBindingRefreshMS}}"
    tags:
      origin: loggregator.syslog_agent

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/counters/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: ingress
    source_id: syslog_agent
    template: "{{.SyslogAgent.DrainIngress}}"
    tags:
      origin: loggregator.syslog_agent
      metric_version: "2.0"
      scope: all_drains

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/counters/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: egress
    source_id: syslog_agent
    template: "{{.SyslogAgent.Egress}}"
    tags:
      origin: loggregator.syslog_agent
      metric_version: "2.0"

- type: replace
  path: /addons/name=loggregator_agent/jobs/name=loggr-expvar-forwarder/properties/counters/-
  value:
    addr: http://127.0.0.1:14822/debug/vars
    name: dropped
    source_id: syslog_agent
    template: "{{.SyslogAgent.EgressDropped}}"
    tags:
      origin: loggregator.syslog_agent
      metric_version: "2.0"

- type: replace
  path: /releases/name=loggregator-agent
  value:
    name: loggregator-agent
    version: latest
