- type: replace
  path: /releases/name=loggregator-agent
  value:
    name: loggregator-agent
    version: latest

- type: replace
  path: /addons/-
  value:
    name: prom_scraper
    include:
      stemcell:
      - os: ubuntu-trusty
      - os: ubuntu-xenial
    jobs:
    - name: prom_scraper
      consumes:
        loggregator:
          from: loggregator
      release: loggregator-agent

- type: replace
  path: /instance_groups/name=doppler/jobs/name=doppler/provides/loggregator?
  value:
    as: loggregator
    shared: true
