- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggr-forwarder-agent-windows?
  value:
    name: loggr-forwarder-agent-windows
    release: loggregator-agent
    properties:
      tls:
        ca_cert: "((loggregator_ca.certificate))"
        cert: "((loggregator_tls_agent.certificate))"
        key: "((loggregator_tls_agent.private_key))"

- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggregator_agent_windows?
  value:
    name: loggregator_agent_windows
    release: loggregator-agent
    properties:
      grpc_port: 3459
      loggregator:
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          agent:
            cert: "((loggregator_tls_agent.certificate))"
            key: "((loggregator_tls_agent.private_key))"
      syslog_daemon_config:
        enable: false

- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggr-system-metrics-agent-windows?
  value:
    name: loggr-system-metrics-agent-windows
    release: loggregator-agent
    properties:
      log_agent:
        ca_cert: "((loggregator_ca.certificate))"
        client_cert: "((system_metrics_agent.certificate))"
        client_key: "((system_metrics_agent.private_key))"

#Delete ME
- type: replace
  path: /releases/name=loggregator-agent
  value:
    name: loggregator-agent
    version: latest
