- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggr-forwarder-agent-windows?
  value:
    name: loggr-forwarder-agent-windows
    release: loggregator-agent
    properties:
      tls:
        ca_cert: "((loggregator_ca.certificate))"
        cert: "((loggregator_tls_agent.certificate))"
        key: "((loggregator_tls_agent.private_key))"

- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggregator_agent_windows/properties/grpc_port?
  value: 3459

- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggr-system-metrics-agent-windows?
  value:
    name: loggr-system-metrics-agent-windows
    release: loggregator-agent
    properties:
      system_metrics:
        tls:
          ca_cert: "((system_metrics.ca))"
          cert: "((system_metrics.certificate))"
          key: "((system_metrics.private_key))"

- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=loggr-syslog-agent-windows?
  value:
    name: loggr-syslog-agent-windows
    release: loggregator-agent
    properties:
      port: 3460
      tls:
        ca_cert: "((loggregator_ca.certificate))"
        cert: "((loggregator_tls_agent.certificate))"
        key: "((loggregator_tls_agent.private_key))"
      cache:
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          cert: "((syslog_agent_api_tls.certificate))"
          key: "((syslog_agent_api_tls.private_key))"
          cn: "binding-cache"

- type: replace
  path: /instance_groups/name=windows1803-cell/jobs/name=prom_scraper_windows?
  value:
    name: prom_scraper_windows
    release: loggregator-agent
