- type: replace
  path: /addons/-
  value:
    name: loggr-system-metrics-agent
    include:
      stemcell:
      - os: ubuntu-xenial
    exclude:
      jobs:
      - name: smoke_tests
        release: cf-smoke-tests
    jobs:
    - name: loggr-system-metrics-agent
      release: loggregator-agent
      properties:
        tls:
          ca_cert: "((loggregator_ca.certificate))"
          cert: "((system_metrics_agent.certificate))"
          key: "((system_metrics_agent.private_key))"
        system_metrics:
          tls:
            ca_cert: "((system_metrics.ca))"
            cert: "((system_metrics.certificate))"
            key: "((system_metrics.private_key))"

- type: replace
  path: /variables/-
  value:
    name: system_metrics
    type: certificate
    options:
      ca: loggregator_ca
      common_name: system-metrics
      extended_key_usage:
      - client_auth
      - server_auth

