name: loggregator-agent

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

releases:
- name: bpm
  version: latest
- name: loggregator-agent
  version: latest

addons:
- name: bpm
  include:
    stemcell:
    - os: ubuntu-trusty
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: standalone-agent
  azs:
  - z1
  instances: 1
  persistent_disk_type: 5GB
  vm_type: minimal
  stemcell: default
  networks:
  - name: default
  jobs:
  - name: loggregator_agent
    release: loggregator-agent
    consumes:
      doppler: {from: doppler, deployment: loggregator}
    properties:
      disable_udp: false
      bosh_dns: true
      loggregator:
        tls:
          ca_cert: "((loggregator_agent.ca))"
          agent:
            cert: "((loggregator_agent.certificate))"
            key: "((loggregator_agent.private_key))"
  - name: forwarder_agent
    release: loggregator-agent

variables:
- name: loggregator_ca
  type: certificate
  options:
    common_name: loggregatorCA
    is_ca: true
- name: loggregator_agent
  type: certificate
  options:
    ca: loggregator_ca
    common_name: agent
    alternative_names:
    - metron
    - agent
    - localhost
    - 127.0.0.1
    - ip6-localhost
    - ::1
    extended_key_usage:
    - client_auth
    - server_auth

update:
  canaries: 10
  max_in_flight: 10
  canary_watch_time: 30000-60000
  update_watch_time: 5000-60000
  serial: true
